### ISSUE TITLE
Check Links fails right after a new release

### ISSUE THREAD

**Issue by jtpio** [jupyter-server/jupyter_releaser#131]
### Problem

When a new release has been published with the commit and tag created on the main branch:

![image](https://user-images.githubusercontent.com/591645/132301471-d5f337ed-cd88-4bc5-9c8d-fe2331c3f51d.png)

The check release script triggered on a new PR can fail with the following:

![image](https://user-images.githubusercontent.com/591645/132240929-9485c70a-9bb6-4645-ac34-cee5bcd1db3d.png)

Example PR: https://github.com/jtpio/ipylab/pull/76
Example run: https://github.com/jtpio/ipylab/runs/3526255104

### Proposed Solution

This seems to be because there is no new change since the last tag when generating the changelog (`None`).

Maybe the fix could be to default the Full Changelog url to use the latest tag instead of `None`.

**Comment by blink1073** [comment]
Fixed by #243
