### ISSUE TITLE
Upload `SHA256SUMS` as a GitHub Release asset

### ISSUE THREAD

**Issue by jtpio** [jupyter-server/jupyter_releaser#133]
### Problem

It is often good practice to upload a `SHA256SUMS` file next to the other release assets for integrity.

### Proposed Solution

We can add a step to the releaser to compute these hashes, and upload them when creating the GitHub Release.

**Comment by blink1073** [comment]
We now upload an `asset_shas.json`.  Can we close this as complete?

**Comment by jtpio** [comment]
Thanks @blink1073.

Do you have an example of a release with a `asset_shas.json` file for reference?

The last releases I made don't seem to have this file as an asset (but that a couple of days ago):

- https://github.com/voila-dashboards/voila/releases/tag/v0.4.0b0
- https://github.com/jupyter/notebook/releases/tag/v7.0.0a6

**Comment by blink1073** [comment]
Here's an example: https://github.com/jupyter-server/jupyter_releaser/releases/tag/v1.0.0a4

**Comment by jtpio** [comment]
Nice thanks!
