### ISSUE TITLE
Handle multiple Python packages

### ISSUE THREAD

**Issue by jtpio** [jupyter-server/jupyter_releaser#169]
### Problem

At the moment the releaser assumes there is a single Python package located at the root of the repository.

There are several checks in the code base that look for a `setup.py` or `pyproject.toml` file. For example:

https://github.com/jupyter-server/jupyter_releaser/blob/9c9902b33172642afa0229fe13d35b66a1cab647/jupyter_releaser/cli.py#L369-L371

However, some repos have multiple Python packages. This is the case for `ipywidgets`: 

- top-level `ipywidgets` package: https://github.com/jupyter-widgets/ipywidgets/blob/master/setup.cfg
- `jupyterlab_widgets` (for the JupyterLab extension): https://github.com/jupyter-widgets/ipywidgets/blob/master/jupyterlab_widgets/setup.cfg
- `widgetsnbextension` (for the classic notebook): https://github.com/jupyter-widgets/ipywidgets/blob/master/widgetsnbextension/setup.cfg

### Proposed Solution

For `npm` packages there is already the concept of workspace `packages`, and is supported by the releaser.

However this doesn't seem to be standardized for Python monorepos. So maybe we could instead have an option to specify a list of directories pointing to the Python packages?

In the case of `ipywidgets` it might look like the following:

```toml
[tools.jupyter-releaser.options]
python_packages = [".", "jupyterlab_widgets", "widgetsnbextension"]
```

The releaser would then build each package from the list, and stage the built assets to the `dist-dir`.

### Additional context

https://github.com/jupyter-widgets/ipywidgets/issues/3285

**Comment by davidbrochart** [comment]
This is also the case for [jupyverse](https://github.com/jupyter-server/jupyverse), where all the plugins are Python packages.

**Comment by jtpio** [comment]
Also the PyPI token map would have to handle PyPI package names instead of the repo names like it is at the moment.
