### ISSUE TITLE
Packages uploaded multiple times

### ISSUE THREAD

**Issue by davidbrochart** [jupyter-server/jupyter_releaser#200]
I just updated my fork of jupyter_releaser to the latest, and trying to release jupyverse [fails](https://github.com/davidbrochart/jupyter_releaser/runs/4090888225?check_suite_focus=true). It looks like it's uploading the packages again and again. For instance, `fps-auth` was uploaded several times, and I can see that the version is there on PyPI, but then we get a `403`.
I'm not sure why it is uploaded several times, any idea?

**Comment by jtpio** [comment]
Thanks @davidbrochart for reporting.

Would you be able to try on a older fork prior to the `0.9` releases? Also this might just affect the Python monorepo setup as other releases with only one Python package at the top-level seem to be going through.

**Comment by davidbrochart** [comment]
I tried with a my fork of jupyter_releaser just after #176 was merged, which used to work fine, and I still get the issue:
https://github.com/davidbrochart/jupyter_releaser/runs/4103406579?check_suite_focus=true
It is not a credential issue because the packages are uploaded to PyPI, so I'm not sure what is going on.

**Comment by blink1073** [comment]
You're still using the `v1` tags of the actions in that build.  My guess is that the publish function is being called once per package name, and then also trying to publish all of the packages each time.

**Comment by davidbrochart** [comment]
Ah, somehow I thought that because I'm running the actions from my fork of jupyter_releaser, it was directly linked to the code in this fork, but IIUC it only uses the actions in my fork and actually runs code from `jupyter-server/jupyter_releaser`:
https://github.com/davidbrochart/jupyter_releaser/blob/5b177428d9aed4903110327848c88be40fa64afa/.github/actions/publish-release/action.yml#L34-L35
