### ISSUE TITLE
Test Against Jupyter Server

### ISSUE THREAD

**Issue by afshin** [jupyter-server/jupyter_releaser#3]
Test this release process against Jupyter Server.  

Add a `check_release` workflow to Jupyter Server, and perform a release of `jupyter_server` to the test PyPI server.  Then we can target the public PyPI server and move this library out of the experimental phase.

Relevant PRs:
https://github.com/jupyter-server/jupyter_server/pull/494
https://github.com/jupyter-server/jupyter_server/pull/498
https://github.com/jupyter-server/jupyter_server/pull/499

**Comment by blink1073** [comment]
<img width="858" alt="image" src="https://user-images.githubusercontent.com/2096628/116780558-2a0da480-aa43-11eb-8722-e50d20f64b38.png">

<img width="823" alt="image" src="https://user-images.githubusercontent.com/2096628/116780561-2e39c200-aa43-11eb-84f5-901b28bccfe5.png">

![big_yes](https://user-images.githubusercontent.com/2096628/116780568-35f96680-aa43-11eb-9596-ea6b616b0deb.gif)

**Comment by blink1073** [comment]
Published https://github.com/jupyter-server/jupyter_server/releases/tag/v1.7.0a1 as well, calling this good!

**Comment by blink1073** [comment]
Also https://pypi.org/project/jupyter-releaser/0.1.0/
