### ISSUE TITLE
Check Release is timing out

### ISSUE THREAD

**Issue by jtpio** [jupyter-server/jupyter_releaser#309]
## Description

Looks like the Check Release workflow is now timing out.

Noticed in a PR as well as in a fork: https://github.com/jtpio/jupyter_releaser/runs/6250705428?check_suite_focus=true

## Reproduce

https://github.com/jupyter-server/jupyter_releaser/runs/6251104386?check_suite_focus=true

![image](https://user-images.githubusercontent.com/591645/166213194-219e749c-3391-49f5-a6e2-3cbf210443eb.png)

## Context

This could be related to the new release of `pypiserver`: https://github.com/pypiserver/pypiserver/releases/tag/v1.5.0

**Comment by wolfv** [comment]
Seeing the same problem with the quetz tests.

**Comment by blink1073** [comment]
Releasing now, my CI token had expired.

**Comment by blink1073** [comment]
Fixed by #308

**Comment by wolfv** [comment]
Awesome, thanks @blink1073 !
