### ISSUE TITLE
Ability to skip the installation of the package in `prep-git`

### ISSUE THREAD

**Issue by jtpio** [jupyter-server/jupyter_releaser#321]
### Problem

Follow-up to https://github.com/jupyter-server/jupyter_releaser/pull/319#pullrequestreview-978029994

Some projects use a top-level `pyproject.toml` to manage configuration for Python monorepos (isort, tbump), without the top-level being installable.

For example JupyterLite: https://github.com/jupyterlite/jupyterlite/blob/main/pyproject.toml

The default installation step in `prep-git` is then causing some issues because the top-level is not installable:

https://github.com/jupyter-server/jupyter_releaser/blob/02418b27b2e7d20f88f3a64877a8fb79964d4c5f/jupyter_releaser/lib.py#L599-L602

### Proposed Solution

Maybe there could be a new releaser configurable option to skip this installation step.

Or the installation step moved to another step, so it can be `skip`-ed

### Additional context

https://github.com/jupyter-server/jupyter_releaser/pull/319#pullrequestreview-978029994

**Comment by blink1073** [comment]
Perhaps we should load the file and check for build metadata?

**Comment by jtpio** [comment]
> Perhaps we should load the file and check for build metadata?

Good point, sounds like this should work :+1:

**Comment by bollwyvl** [comment]
It looks like `pip` might actually back up some of these changes (or introduce flags), as it broke _way_ more just flit editable installs.
