### ISSUE TITLE
[Github Action] "check-links" adds `:` to target url, and fails.

### ISSUE THREAD

**Issue by a3626a** [jupyter-server/jupyter_releaser#339]
## Description

During full-release, "check-links" runs.
```
--------------------------------------------------
check-links
--------------------------------------------------
Checking files with options:
/opt/hostedtoolcache/Python/3.10.5/x64/bin/python -m pytest --noconftest --check-links --check-links-cache --check-links-cache-expire-after 604800 -raXs --color yes --quiet --check-links-cache-name /home/runner/.cache/releaser-link-check/check-release-links -p no:doctest -c _IGNORE_CONFIG --check-links-ignore "https://github.com/.*/(pull|issues)/.*" --check-links-ignore "https://github.com/search?" --check-links-ignore "http://localhost.*" --check-links-ignore "https://docs.github.com/.*" --ignore-glob node_modules
```

And it fails. [This](https://github.com/team-monolith-product/jupyterlab-reset-fixer/tree/231ce906d945c304121df32b563f26832c52f8b5) is target repository.

```
--------------------------------------------------------------------------------
RELEASE.md...
....
4 passed in 0.90s
--------------------------------------------------------------------------------
CHANGELOG.md...
no tests ran in 0.33s
--------------------------------------------------------------------------------
README.md...
Error: /home/runner/work/jupyter_releaser/jupyter_releaser/.jupyter_releaser_checkout/README.md: https://playwright.dev/docs/intro/
https://playwright.dev/docs/intro/: 404: Not Found
....F...                                                                 [100%]
=================================== FAILURES ===================================
_ /home/runner/work/jupyter_releaser/jupyter_releaser/.jupyter_releaser_checkout/README.md: https://playwright.dev/docs/intro/ _
https://playwright.dev/docs/intro/: 404: Not Found
=========================== short test summary info ============================
FAILED README.md::/home/runner/work/jupyter_releaser/jupyter_releaser/.jupyter_releaser_checkout/README.md <a href=https://playwright.dev/docs/intro/>
1 failed, 7 passed in 1.32s
README.md (second attempt)...
Error: /home/runner/work/jupyter_releaser/jupyter_releaser/.jupyter_releaser_checkout/README.md: https://playwright.dev/docs/intro/
https://playwright.dev/docs/intro/: 404: Not Found
F                                                                        [100%]
=================================== FAILURES ===================================
_ /home/runner/work/jupyter_releaser/jupyter_releaser/.jupyter_releaser_checkout/README.md: https://playwright.dev/docs/intro/ _
https://playwright.dev/docs/intro/: 404: Not Found
=========================== short test summary info ============================
FAILED README.md::/home/runner/work/jupyter_releaser/jupyter_releaser/.jupyter_releaser_checkout/README.md <a href=https://playwright.dev/docs/intro/>
1 failed, 7 deselected in 0.37s
```

[README.md](https://github.com/team-monolith-product/jupyterlab-reset-fixer/blob/231ce906d945c304121df32b563f26832c52f8b5/README.md) contains "`https://playwright.dev/docs/intro/`", not "`https://playwright.dev/docs/intro/:`".

```
...
This extension uses [Playwright](https://playwright.dev/docs/intro/) for the integration tests (aka user level tests).
...
```

## Reproduce
1. Create a new jupyter lab extension following [tutorial](https://jupyterlab.readthedocs.io/en/stable/extension/extension_tutorial.html)
2. Fork this repository.
3. Put every required secrets.
4. Run full-release

## Expected behavior
`pytest` should verifies connection to `https://playwright.dev/docs/intro/`, not `https://playwright.dev/docs/intro/:`
(and success.)

## Context
- Operating System and version: 100% running on github actions. Synced to main branch [here](https://github.com/jupyter-server/jupyter_releaser/tree/eb66cf814e5c3f8de512f43b34e2e6fcc11367f7).

**Comment by blink1073** [comment]
Hi @a3626a, I think the colon comes from the report and is not the link that was actually checked.  When I went to the link in my browser I see the page flash with a 404 error and then load, I think something is strange about the way the site is loaded.  You might need to add the site to an [ignore-links](https://github.com/jupyterlab/jupyterlab/blob/cb117e3c0767f3fcfd734f3cc84b058b22b414c9/pyproject.toml#L32) config.

**Comment by a3626a** [comment]
> Hi @a3626a, I think the colon comes from the report and is not the link that was actually checked. When I went to the link in my browser I see the page flash with a 404 error and then load, I think something is strange about the way the site is loaded. You might need to add the site to an [ignore-links](https://github.com/jupyterlab/jupyterlab/blob/cb117e3c0767f3fcfd734f3cc84b058b22b414c9/pyproject.toml#L32) config.

Thank you for your reply.

I agree with you :
![image](https://user-images.githubusercontent.com/4434752/177499219-ea2d98a9-dce6-4dca-b334-cbaa38aa04a9.png)
