### ISSUE TITLE
Full release fails

### ISSUE THREAD

**Issue by 3coins** [jupyter-server/jupyter_releaser#421]
## Description
Full release is failing for `jupyter-server/jupyter-scheduler` even though the  Prep Release has created a correct Draft release. The error displayed refers to this message.

```
From https://github.com/3coins/jupyter_releaser
 * branch            main       -> FETCH_HEAD
4aa69439e685654f36cebcd14f6c11fbcdfc930b
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.7/x[64](https://github.com/3coins/jupyter_releaser/actions/runs/3184091969/jobs/5192100306#step:4:67)/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/actions/populate_release.py", line 34, in <module>
    ensure_sha()
Prepare Environment
    raise ValueError(f"{branch} is ahead of expected sha {current_sha}")
ValueError: main is ahead of expected sha 5fd185[69](https://github.com/3coins/jupyter_releaser/actions/runs/3184091969/jobs/5192100306#step:4:72)10bc2d90bb5c1c24cdfd06c6e351e160
```
The sha referred to the error message seems correct, as per the changelog here, so not sure what is expected.
https://github.com/jupyter-server/jupyter-scheduler/compare/v0.3.1...5fd1856910bc2d90bb5c1c24cdfd06c6e351e160

## Context
Prep Release Run
https://github.com/3coins/jupyter_releaser/actions/runs/3184039435

Full Release Run
https://github.com/3coins/jupyter_releaser/actions/runs/3184091969/jobs/5192100306

**Comment by blink1073** [comment]
That error is most likely due to merging a PR between when prep release and publish release were run.

**Comment by 3coins** [comment]
@blink1073 That’s what I thought initially, but this was not the case. This is the 2nd time I saw this error and had to do a manual release.

**Comment by blink1073** [comment]
Nothing is jumping out at me.  I'm adding more debugging in #422

**Comment by blink1073** [comment]
I pushed a release with the extra debugging added.

**Comment by blink1073** [comment]
This is still not working, we need to make `ensure-sha` a CLI command and have it run from the checkout directory.
