### ISSUE TITLE
Publish Release workflow: `Error: No such command 'ensure-sha'`

### ISSUE THREAD

**Issue by jtpio** [jupyter-server/jupyter_releaser#438]
## Description

Just synced the releaser fork to the latest and getting the following when running the "Publish Release" workflow:

```
 Initialized empty Git repository in /home/runner/work/jupyter_releaser/jupyter_releaser/.jupyter_releaser_checkout/.git/
Switched to a new branch 'main'
branch 'main' set up to track 'origin/main'.
refs/heads/main
Usage: jupyter-releaser [OPTIONS] COMMAND [ARGS]...
Try 'jupyter-releaser --help' for help.

Error: No such command 'ensure-sha'.
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/jupyter_releaser/actions/populate_release.py", line 30, in <module>
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/jupyter_releaser/actions/common.py", line 21, in run_action
    _run(target, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/jupyter_releaser/util.py", line 92, in run
    log("stdout:\n", e.stdout.strip(), "\n\n")
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/jupyter_releaser/util.py", line 84, in run
    try:
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/jupyter_releaser/tee.py", line 155, in run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command 'jupyter-releaser ensure-sha' returned non-zero exit status 2.
Prepare Environment
jupyter-releaser prep-git
```

## Reproduce

Example run: https://github.com/jtpio/jupyter_releaser/actions/runs/3219545693/jobs/5265049713

Happening while trying to release voila: https://github.com/voila-dashboards/voila/releases/tag/untagged-e54d686da3fbaad8aa3c

## Context

This looks related to the changes in https://github.com/jupyter-server/jupyter_releaser/pull/435.

**Comment by blink1073** [comment]
I'm not sure what is going on, I just did the following locally and it was fine:

```bash
$ pip install -q git+https://github.com/jupyter-server/jupyter_releaser.git@v2
$ jupyter-releaser --help
Usage: jupyter-releaser [OPTIONS] COMMAND [ARGS]...

  Jupyter Releaser scripts

Options:
  --force BOOLEAN  Force a command to run even when skipped by config
  --help           Show this message and exit.

Commands:
  list-envvars           List the environment variables
  prep-git               Prep git and env variables and bump version
  bump-version           Prep git and env variables and bump version
  extract-changelog
  build-changelog        Build changelog entry
  draft-changelog        Create a changelog entry PR
  build-python           Build Python dist files
  check-python           Check Python dist files
  build-npm              Build npm package
  check-npm              Check npm package
  tag-release            Create release commit and tag
  populate-release
  delete-release         Delete a draft GitHub release by url to the...
  extract-release        Download and verify assets from a draft GitHub...
  publish-assets         Publish release asset(s)
  publish-release        Publish GitHub release
  ensure-sha
  forwardport-changelog  Forwardport Changelog Entries to the Default Branch
```

I also just used releaser to release maintainer-tools: https://github.com/blink1073/jupyter_releaser/actions/runs/3219472835

**Comment by jtpio** [comment]
> I also just used releaser to release maintainer-tools: https://github.com/blink1073/jupyter_releaser/actions/runs/3219472835

But this repo doesn't publish assets to PyPI right?

**Comment by blink1073** [comment]
Can you try releasing a "next" release of maintainer-tools?

**Comment by jtpio** [comment]
Sure

**Comment by jtpio** [comment]
Looks like it went through: https://github.com/jupyterlab/maintainer-tools/releases/tag/v0.15.2

Also I'm not sure why but in the case of the Voila release it opened a Automated Changelog Entry PR after running the "Step 1: Prep Release" workflow:

- https://github.com/voila-dashboards/voila/pull/1231
- https://github.com/jtpio/jupyter_releaser/actions/runs/3219387473/jobs/5264693264

While in the case of `maintainer-tools` the changes were updated in place in the draft GitHub release.

**Comment by jtpio** [comment]
Maybe the missing `ensure-sha` command is because the voila repo defines a dependency on `jupyter_releaser~=0.25` here (used for the bump version script): https://github.com/voila-dashboards/voila/blob/8e1a3f3fb7bf4f4d49e04a95a1e6a59ecd39d9eb/pyproject.toml#L57

Which might be installed quietly during the `prep-git` step? 

https://github.com/jupyter-server/jupyter_releaser/blob/7e78643e9827c1e33187992dffa09debc259ce4a/jupyter_releaser/lib.py#L495

**Comment by blink1073** [comment]
Ah, that might do it

**Comment by jtpio** [comment]
This seems to be passing now after removing the pin on `jupyter_releaser` in the `dev` dependencies: https://github.com/voila-dashboards/voila/pull/1232.

That way the bump version script uses the latest version of `jupyter_releaser` installed during the `prep-git` step.

Wondering whether there should be some isolation when installing the package with `pip install -q -e ".[dev,test]"`, since there might be some dependencies in the `dev` or `test` extras that could conflict with the latest `jupyter_releaser` (or one of its dependencies).

Closing as fixed.
