### ISSUE TITLE
Install package in venv

### ISSUE THREAD

**Issue by blink1073** [jupyter-server/jupyter_releaser#440]
We should consider "some isolation when installing the package with pip install -q -e ".[dev,test]", since there might be some dependencies in the dev or test extras that could conflict with the latest jupyter_releaser (or one of its dependencies)."

https://github.com/jupyter-server/jupyter_releaser/issues/438#issuecomment-1274204085

**Comment by jtpio** [comment]
Removing the install of the python packages sounds good, or at least worth trying for v2.

Probably there could be some `dev` packages that are used to bump the version for example. But they could also be installed in one of the releaser hooks as well, for example in `after-prep-git` or `before-bump-version`.
