### ISSUE TITLE
NPM pack fails to pack `lib` on v2 but works ok on v1

### ISSUE THREAD

**Issue by krassowski** [jupyter-server/jupyter_releaser#474]
I am a bit lost here but a JupyterLab extension seeded from coookiecutter after releaser v2 migration has a failure on CI on release check action as npm pack results (`build-npm`) seems to ignore most of the relevant files (it only includes `styles/` `README`, `LICENSE`, and `package.json`).

I tried a number of things, such as adding `.npmignore`, changing `files` entry, adding build step in `before-build-npm`, removing `.gitignore`, and verified that:
- none of the above helps
- `ls`/`tree` shows that `lib` is in there indeed
- manual `npm pack` in a step prior to check-release works as expected

Further, downgrading to `@v1` also seems to fix this issue (but then it fails on `check-links`, on `.jupyter_releaser_checkout/README.md` which is rather unexpected).

For logs see https://github.com/krassowski/ui-profiler/pull/1

**Comment by krassowski** [comment]
Should I expect to see `before-build-npm` in logs? I don't see it, could it be the root cause?

**Comment by jtpio** [comment]
@krassowski iirc I saw something similar recently with another lab extension while trying to update to v2.

It might be because the cookiecutter defines bits of the releaser config in both `pyproject.toml` and `package.json`:

https://github.com/jupyterlab/extension-cookiecutter-ts/blob/4fca73f34a69bb6ce1e88b4f7eef6d56d92c0c3d/%7B%7Bcookiecutter.python_name%7D%7D/pyproject.toml#L77

And maybe the releaser then ignores the config `package.json` if it's already found in `pyproject.toml`. If that's the case we can update the cookiecutter to put the config in one place only.

**Comment by krassowski** [comment]
I tried adding hooks to `pyproject.toml` in https://github.com/krassowski/ui-profiler/commit/3f8b07c1375903cf9f1bb04fa144cab1eaed8d81 but it did not help. It seems that `before-build-npm` is not triggered in v2. An additional piece of evidence is that when I remove `files` field from `package.json` I get `src` in the tarball but not `lib`.

**Comment by krassowski** [comment]
No sorry, after moving the hooks into `pyproject.toml` it works. I mean `before-build-npm` gets executed. Maybe I need to revert some other changes that I attempted to make it work fully again. Thank you for the hint!

**Comment by jtpio** [comment]
Maybe re-adding `jlpm build:prod` script will help, since the cookiecutter does not have any special `npm` script like `prepare` anymore?

**Comment by krassowski** [comment]
Yes, that was it: https://github.com/krassowski/ui-profiler/pull/1/commits/2e074ad8d503e94b50ccacca8ce73eba382cd801.

Do we want to fix it here by merging configuration from multiple sources, or in cookiecutter (and by adding a warning in documentation about precedence and exclusivity of configuration sources)?

**Comment by jtpio** [comment]
> Do we want to fix it here by merging configuration from multiple sources, or in cookiecutter (and by adding a warning in documentation about precedence and exclusivity of configuration sources)?

Good question. For sure the config in the cookiecutter could be moved to `pyproject.toml` just to avoid confusion and keep everything in the same place.

Supporting reading partial config from `pyproject.toml`, `package.json` and other files could be seen as a feature. But it could also be confusing to know which one takes precedence if the same config (for example `version-cmd`) is defined in multiple files. So yes maybe it's better to encourage placing the releaser config in a single file only and document it.

**Comment by krassowski** [comment]
Closing this issue as the documentation of releaser actually does mention that only the first found configuration source is used:

https://github.com/jupyter-server/jupyter_releaser/blob/main/docs/source/how_to_guides/write_config.md?plain=1#L28-L32

I opened PRs on cookiecutter repository. Thanks again!
