### ISSUE TITLE
Unauthorized to make releases

### ISSUE THREAD

**Issue by martinRenou** [jupyter-server/jupyter_releaser#494]
## Description

I cannot make releases with the releaser anymore and getting:

```
Getting GitHub connection for jupyterlite/xeus-python-kernel
Getting permission level for martinRenou
HTTP Error 401: Unauthorized
```

For example here: https://github.com/martinRenou/jupyter_releaser/actions/runs/4135041940/jobs/7147044143

This happens on the `jupyterlite` org which I am an owner of (see screenshot)
 
![Screenshot from 2023-02-09 15-10-46](https://user-images.githubusercontent.com/21197331/217835966-60a3184e-1358-4cdd-95c1-6a8857b510c0.png)

**Comment by martinRenou** [comment]
I thought it could be because I'm an admin of `jupyterlite/xeus-python-kernel` only through the `xeus-kernels` team in jupyterlite, but even explicitly adding myself as an admin of that repo did not fix it

![Screenshot from 2023-02-09 15-20-11](https://user-images.githubusercontent.com/21197331/217838419-9cfcab6c-04fb-460b-a531-472da9196fdb.png)

**Comment by blink1073** [comment]
Perhaps your `ADMIN_GITHUB_TOKEN` has expired, or perhaps it is a newer, scoped token?

**Comment by martinRenou** [comment]
Thank you for you answer! I haven't thought of this, I thought this was to be set only once but it's true that they have a limited time of validity. I will check it out.

**Comment by jtpio** [comment]
FYI @martinRenou this will help make new releases from the repo directly and remove the need of maintaining the releaser fork: https://github.com/jupyterlite/xeus-python-kernel/pull/109

**Comment by krassowski** [comment]
I think I am hitting something similar with a fork workflow:

```
Getting GitHub connection for @jupyterlab/ui-profiler
Getting permission level for krassowski
HTTP Error 404: Not Found
```

I've re-generated the token and it is still showing up.

**Comment by krassowski** [comment]
User was to blame here - I need more coffee. For some weird reason I was wrongly adding "@" before the organisation name.
