### ISSUE TITLE
Only publish to NPM

### ISSUE THREAD

**Issue by danyrouh** [jupyter-server/jupyter_releaser#508]
Hello,
I'm trying to use your tool to publish a jupyterlab extension (client typescript, backend python) to npmjs only and exclude pypi for now.  I keep getting this error:
ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
         Invalid or non-existent authentication information. See
         https://pypi.org/help/#invalid-auth for more information.

I tried every configuration I can find online, which are not many, with no luck so far.  I added the following two command lines to the finalize release section.  It did nt owork.
  twine-cmd: 'twine upload --skip-existing --verbose dist/*'
   npm_cmd: 'npm publish --tag next'

I removed the authentication part for pypi.  Nothing worked so far.  

Sorry, for sending a request like this, but my experience with the jupyterlab forum has not been positive to date.  I never get any response to my inquiries.

Is what I'm trying to do doable using your tool?  If it is not, I believe it is a good feature to have.

Thanks!
Dany

**Comment by blink1073** [comment]
Hi @danyrouh, you can avoid building the python dist files by skipping the `build-python` step.

```
[tool.jupyter-releaser]
skip = ["build-python"]
````
