### ISSUE TITLE
Emit a log line when Python publishing is skipped due to inconsistent package names

### ISSUE THREAD

**Issue by mahendrapaipuri** [jupyter-server/jupyter_releaser#554]
### Problem

When Python packages name differ in `jupyter-releaser` config and project's `pyproject.toml`, [this check](https://github.com/jupyter-server/jupyter_releaser/blob/81555cfd6a1708ad87130b822dab7e4891fd99cb/jupyter_releaser/lib.py#L430) fails and publishing assets to PyPI will be skipped. Mostly it can happen due to inconsistent use of "hypens" and "underscores" in package names.

When this happens, `jupyter-releaser` will skip publishing without any warnings. It will emit the [No files found](https://github.com/jupyter-server/jupyter_releaser/blob/81555cfd6a1708ad87130b822dab7e4891fd99cb/jupyter_releaser/lib.py#L450) but this is not entirely true as wheels and sdists files are present. This happend on the release of `jupyterlab-topbar` (see [113](https://github.com/jupyterlab-contrib/jupyterlab-topbar/issues/113)) and it was not immediately clear on why publishing has been skipped.

### Proposed Solution

Emit a log line showing the differences in package names can be useful to debug the issue faster.

**Comment by blink1073** [comment]
Thanks for the report @mahendrapaipuri, are you available to make a PR?

**Comment by mahendrapaipuri** [comment]
Sure @blink1073 , I can put up a PR!
