### ISSUE TITLE
Ability to allow for non-admin user execution

### ISSUE THREAD

**Issue by ElioDiNino** [jupyter-server/jupyter_releaser#555]
### Problem

I have modified the default jupyter_releaser workflow such that a GitHub app token is used instead of a user token. However, within the `prepare_environment` function, a check is made through the GitHub API to see if the user is a repo admin ([exact lines here](https://github.com/jupyter-server/jupyter_releaser/blob/v2/jupyter_releaser/util.py#L605-L618)). This is an issue since even though the token is setup such that all the necessary permissions are granted, this arbitrary check blocks non-admin repo members from making releases.

I tried getting around this by modifying the actions with `GITHUB_ACTOR` and setting the value to our bot username, but the GitHub app isn't treated as a user by the API (understandably) and so it fails.

![image](https://github.com/jupyter-server/jupyter_releaser/assets/52972357/ee3b1f98-dc22-4e8b-a28b-326baa57de2e)

### Proposed Solution

I think [the check](https://github.com/jupyter-server/jupyter_releaser/blob/v2/jupyter_releaser/util.py#L605-L618) should either change to validate the required permissions of the token, or for an easier workaround, be able to be turned off through a flag/environment variable (e.g. `RH_ADMIN_CHECK=false`).

### Additional context

<!-- Add any other context or screenshots about the feature request here. You can also include links to examples of other programs that have something similar to your request. For example:

* Another project [...] solved this by [...]

**Comment by ElioDiNino** [comment]
@blink1073 Would you be able to give some thoughts on this? I can implement the latter proposed solution pretty easily and quickly if you approve of it.

**Comment by blink1073** [comment]
Hi @ElioDiNino, I think an `RH_ADMIN_CHECK` with a default of `true` makes sense.

**Comment by ElioDiNino** [comment]
> Hi @ElioDiNino, I think an `RH_ADMIN_CHECK` with a default of `true` makes sense.

Okay, thanks! I will create a PR for that soon

**Comment by ElioDiNino** [comment]
Relevant changes in #559

**Comment by ElioDiNino** [comment]
Resolved with the latest release 🎉
