### ISSUE TITLE
Show the original error message from GitHub on Admin Check

### ISSUE THREAD

**Issue by blink1073** [jupyter-server/jupyter_releaser#579]
## Description

The message for when the admin check fails makes some assumptions about the API response, but we should include the full API response to help debugging.

**Comment by blink1073** [comment]
@ianthomas23, from what I can tell we are logging the full response, https://github.com/jupyter-server/jupyter_releaser/blob/2fc7de9eaad3c36905862ff37a28bf222fb2f254/jupyter_releaser/util.py#L610.

Can you post a link to your workflow run here?

**Comment by ianthomas23** [comment]
@blink1073 https://github.com/ipython/ipykernel/actions/runs/9699310606/job/26767956167 is the latest run in which the Admin check failed.

**Comment by blink1073** [comment]
Oh, right, that was before we backported the workflow changes.  I realized what went wrong after that, we needed to set the branch field in the dialog.  I opened #581 to properly handle the case where you run the workflow against a different branch.
