### ISSUE TITLE
publish-assets error

### ISSUE THREAD

**Issue by brichet** [jupyter-server/jupyter_releaser#595]
## Description

the `publish-assets` action seems to fail on some repo:
- jupyterlab https://github.com/jupyterlab/jupyterlab/pull/16988, https://github.com/jupyterlab/jupyterlab/pull/16989
- jupyter-chat https://github.com/jupyterlab/jupyter-chat/pull/106

Maybe more jupyter repo...

## Reproduce

open a PR in one of the above repository

## Expected behavior

The test to pass

## Context

This is probably due to the last release of `pypiserver` https://github.com/pypiserver/pypiserver/releases/tag/v2.3.0

### Note

I tried to reproduce it in the `jupyter_releaser` repository in https://github.com/jupyter-server/jupyter_releaser/pull/594, which run the same action and used the same [version of pypiserver 2.3.2](https://github.com/jupyter-server/jupyter_releaser/actions/runs/12010202990/job/33476547945?pr=594#step:4:112), without success.

**Comment by krassowski** [comment]
Here is the output with `--verbose` from https://github.com/jupyterlab/jupyterlab/pull/16997:

```
Uploading jupyterlab-4.4.0a1-py3-none-any.whl
  0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/11.9 MB • --:-- • ?
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.9/11.9 MB • 00:00 • 178.0 MB/s
INFO     Response from http://0.0.0.0:8081/:
         400 Bad Request
INFO    
             <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
             <html>
                 <head>
                     <title>Error: 400 Bad Request</title>
                     <style type="text/css">
                       html {background-color: #eee; font-family: sans-serif;}
                       body {background-color: #fff; border: 1px solid #ddd;
                             padding: 15px; margin: 15px;}
                       pre {background-color: #eee; border: 1px solid #ddd;
         padding: 5px;}
                     </style>
                 </head>
                 <body>
                     <h1>Error: 400 Bad Request</h1>
                     <p>Sorry, the requested URL
         <tt>&#039;http://0.0.0.0:8081/&#039;</tt>
                        caused an error:</p>
                     <pre>MultipartError: Memory limit reached.</pre>
                 </body>
             </html>
ERROR    HTTPError: 400 Bad Request from http://0.0.0.0:8081/
         Bad Request
```

As to why it did not show up on https://github.com/jupyter-server/jupyter_releaser/pull/594 I think it is because this repo produces much smaller wheel:

```
Uploading jupyter_releaser-1.8.5-py3-none-any.whl
  0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/54.5 kB • --:-- • ?
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 kB • 00:00 • 148.8 MB/s
```

**Comment by brichet** [comment]
> As to why it did not show up on #594 I think it is because this repo produces much smaller wheel:

Maybe yes, but `jupyterlab-chat` is not that big for example... even if it seems too big for the expected contents.

**Comment by krassowski** [comment]
Pinning confirms that all 2.3.x versions fail:
- pypiserver-2.2.0 - pass (https://github.com/jupyterlab/jupyterlab/actions/runs/12028321745/job/33532030493)
- pypiserver-2.3.0 - fail (https://github.com/jupyterlab/jupyterlab/actions/runs/12028321745/job/33531198446)
- pypiserver-2.3.1 - fail (https://github.com/jupyterlab/jupyterlab/actions/runs/11995309231/job/33438682393)
- pypiserver-2.3.2 - fail (https://github.com/jupyterlab/jupyterlab/actions/runs/12027924547/job/33529937436)

**Comment by krassowski** [comment]
I opened upstream issue and a PR to pin the version to 2.2.0 in the meantime:
- https://github.com/pypiserver/pypiserver/issues/630
- https://github.com/jupyter-server/jupyter_releaser/pull/596
